### ISSUE TITLE
Long pressing Catppuccin theme message in Aliucord fails to invoke the Plugin Installer

### ISSUE THREAD

**Issue by midnitefox** [catppuccin/aliucord#2]
From what I can gather, the Plugin Installer only gets called when the message that is long pressed has a complete Github link. As of right now, that link is intentionally segmented. Perhaps so as to prevent a Github preview from showing in the message.

Recommend that the Github link in the message be changed to this:

`<https://github.com/catppuccin/aliucord>`

This will allow the plugin installer to detect it *and* it will prevent the Github embedded preview from showing up.

**Comment by isabelincorp** [comment]
Ah, so for me long pressing works completely fine, but I **can't** go in and edit the message either way because I don't have the theme pass role. 

Personally I think it looks fine, if you mean the catppuccin dot com link being segmented, yea I did that because of embedded links that you can't just get rid of.

![image](https://user-images.githubusercontent.com/114378481/198421819-a89c0ca8-64ee-4cf8-8311-bce98d348365.png)

In here, long pressing the text works, you were probably long pressing the image, so I'm gonna mark this as won't fix.

![image](https://user-images.githubusercontent.com/114378481/198423725-1a7da65e-ac1e-4f57-b8c9-3dacfbdad680.png)
